### ISSUE TITLE
Image representing who is speaking in Minecraft does not reflect skin changes

### ISSUE THREAD

**Issue by Canada-LaVearn** [Cojomax99/JustEnoughDiscordIntegration#3]
As the title says, the image in the discord channel that represents the user does not change when the user changes their skin.

**Comment by Cojomax99** [comment]
This was fixed in #4 - v1.1 coming out soon on CurseForge!

**Comment by itsdinkd** [comment]
So uh. its been 2 months, almost 3, is that going to be on curseforge any sooner by chance
